MovieApp.Web/Models/Message.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace MemoMate.Web.Models
{
	public class Message
	{
		[Column("message_id")]
		public int ID { get; set; }
		[Column("user_from_id")]
		public int UserFromID { get; set; }
		[Column("user_target_id")]
		public int UserTargetID { get; set; }
		[Column("message_content")]
		public string Content { get; set; }
		[Column("sent_date")]
		public DateTime SentDate { get; set; }
	}
}

MovieApp.Web/Models/Messages/ChatRead.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace MemoMate.Web.Models.Messages
{
    public class ChatRead
    {
        [Column("chat_read_id")]
        public int ID { get; set; }
        [Column("user_from_id")]
        public int FromID { get; set; }
        [Column("user_target_id")]
        public int TargetID { get; set; 
        }
        [Column("is_read")]
        public bool IsRead { get; set; }
    }
}

MovieApp.Web/Models/Messages/UserMessagesModel.cs
using System.Collections.Generic;
namespace MemoMate.Web.Models.Messages
{
	public class UserMessagesModel
	{
		public UserEntity LoggedUserEntity { get; set; }
		public Dictionary<UserEntity, Message> Messages { get; set; }
	}

	public class SelectedUserMessages
	{
		public UserEntity LoggedUser { get; set; }
		public UserEntity User { get; set; }
		public List<Message> Messages { get; set; }
	}
}

MovieApp.Web/Models/Post.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace MemoMate.Web.Models
{
    public class Post
    {

        [Column("post_id")]
        public int ID { get; set; }


        [Column("note_id")]
        public int NoteID { get; set; }


        [Column("user_id")]
        public int UserID { get; set; }


        [Column("post_date")]
        public DateTime Date { get; set; }

        [Column("rate_ups")]
        public int RateUps { get; set; }

        [Column("rate_count")]
        public int RateCount { get; set; }

        [Column("check_out")]
        public bool CheckOut { get; set; }

        [Column("theme_id")]
        public int ThemeID { get; set; }

        public Note NoteEntity { get; set; }
        public UserEntity UserEntity { get; set; }
        public Theme ThemeEntity { get; set; }
    }
}

MovieApp.Web/Models/Posts/PostDetailModel.cs
using System;

namespace MemoMate.Web.Models.Posts
{
    public class PostDetailModel
    {
        public int PostID { get; set; }
        public int UserID { get; set; }
        public DateTime PostDate { get; set; }
        public string NoteTitle { get; set; }
        public string NoteContent { get; set; }
        public float PostRate { get; set; }
        public string Username { get; set; }
        public string UserPhoto { get; set; }
        public string ThemeName { get; set; }
        public string Liked { get; set; }
        public string FriendStatus { get; set; }
        public bool IsOwned { get; set; }
        public bool CanInteract { get; set; }
    }
}

MovieApp.Web/Models/Posts/PostsViewModel.cs
using System.Collections.Generic;

namespace MemoMate.Web.Models.Posts
{
    public class PostsViewModel
    {
        public UserEntity LoggedUserEntity { get; set; }
        public Theme TodayTheme { get; set; }
        public string YesterdayThemeName { get; set; }
        public List<PostDetailModel> PostsYesterday { get; set; }
        public List<PostDetailModel> PostsCheckOut { get; set; }
    }
}

MovieApp.Web/Models/Posts/RateViewModel.cs
namespace MemoMate.Web.Models.Posts
{
    public class RateViewModel
    {
        public UserEntity LoggedUserEntity { get; set; }
        public PostDetailModel RatePost { get; set; }
        public bool like { get; set; }
    }
}

MovieApp.Web/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Mvc;
using MemoMate.Web.Models;
using MemoMate.Web.Models.Messages;
using MemoMate.Data;
using System.Linq;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System;
using MemoMate.Web.Hubs;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.DependencyInjection;

namespace MemoMate.Web.Controllers
{
	[Authorize(Policy = "General")]
	public class MessagesController : Controller
	{
		private readonly MemoMateContext _context;
		public MessagesController(MemoMateContext context)
		{
			_context = context;
		}


		public async Task<IActionResult> Inbox()
		{
			UserMessagesModel model = await GetTalkedUsers();
			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> GetMessages(string username, int skip)
		{
			if (string.IsNullOrEmpty(username))
				return NoContent();

			UserEntity selectedUser = await _context.Users.Where(u => u.Username == username).FirstOrDefaultAsync();
			int loggedID = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);

			if (selectedUser == null) return NoContent();
			SelectedUserMessages model = new SelectedUserMessages()
			{
				LoggedUser = await _context.Users.Where(u => u.ID == loggedID).FirstOrDefaultAsync(),
				User = selectedUser,
				Messages = await GetUserMessages(selectedUser.ID, skip, null)
			};
			if (model.Messages.Count == 0)
				return NoContent();

			return PartialView("_UserMessagesPartial", model);
		}

		private async Task<UserMessagesModel> GetTalkedUsers()
		{
			var loggedUser = await _context.Users.Where(u => u.ID == int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value)).FirstAsync();
			Dictionary<UserEntity, Message> messages = new Dictionary<UserEntity, Message>();
			List<int> userIds = await _context.Messages
									 .Where(m => m.UserFromID == loggedUser.ID || m.UserTargetID == loggedUser.ID)
									 .Select(m => m.UserFromID == loggedUser.ID ? m.UserTargetID : m.UserFromID)
									 .Distinct().ToListAsync();

			for (int i = 0; i < userIds.Count; i++)
			{
				int userID = userIds[i];
				var talkUser = await _context.Users.Where(u => u.ID == userID).FirstAsync();
				var lastMessage = await _context.Messages
									 .Where(m => (m.UserFromID == loggedUser.ID && m.UserTargetID == userID) || (m.UserFromID == userID && m.UserTargetID == loggedUser.ID))
									 .OrderByDescending(m => m.SentDate)
									 .FirstAsync();
				if (lastMessage.Content.Length > 50)
					lastMessage.Content = lastMessage.Content.Substring(0, 40);
				messages.Add(talkUser, lastMessage);
			}

			UserMessagesModel model = new UserMessagesModel()
			{
				LoggedUserEntity = loggedUser,
				Messages = messages
			};
			return model;
		}

		private async Task<List<Message>> GetUserMessages(int selectedUserId, int skip, int? take)
		{
			int userId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
			return await _context.Messages.Where(m => (m.UserFromID == selectedUserId && m.UserTargetID == userId)
						 || (m.UserFromID == userId && m.UserTargetID == selectedUserId)).
						 OrderByDescending(m => m.SentDate)
						 .Skip(skip)
						 .Take(20)
						 .ToListAsync();
		}

		[HttpGet]
		public async Task<IActionResult> SendMessage(string username, string message)
		{
			if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(message))
				return NoContent();

			var targetUser = await _context.Users
								   .Where(u => u.Username == username)
								   .FirstOrDefaultAsync();
			if (targetUser == null)
				return NoContent();


			var fromUser = await _context.Users
								   .Where(u => u.ID == int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value))
								   .FirstOrDefaultAsync();

			Message newMessage = new Message()
			{
				SentDate = DateTime.Now,
				UserFromID = fromUser.ID,
				UserTargetID = targetUser.ID,
				Content = message
			};

			await _context.Messages.AddAsync(newMessage);
			await _context.SaveChangesAsync();

			var hubContext = HttpContext.RequestServices.GetService<IHubContext<ChatHub>>();

			// Kullanıcı adından kullanıcı kimliğine dönüşüm yaparak mesajı iletin
			await hubContext.Clients.User(targetUser.ID.ToString()).SendAsync("ReceiveMessage", fromUser.Username);

			SelectedUserMessages model = new SelectedUserMessages()
			{
				LoggedUser = await _context.Users.Where(u => u.ID == int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value)).FirstOrDefaultAsync(),
				User = targetUser,
				Messages =
				new List<Message>
				{
					newMessage
				}
			};
			await SetMessageRead(read: false, fromID: fromUser.ID, targetID: targetUser.ID);
			return PartialView("_UserMessagesPartial", model);
		}



		[HttpGet]
		public async Task<IActionResult> GetLastMessage(string username)
		{
			if (string.IsNullOrEmpty(username))
				return NoContent();

			int loggedUserID = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
			UserEntity selectedUser = await _context.Users.Where(u => u.Username == username).FirstOrDefaultAsync();

			if (selectedUser == null) return NoContent();
			SelectedUserMessages model = new SelectedUserMessages()
			{
				LoggedUser = await _context.Users.Where(u => u.ID == loggedUserID).FirstOrDefaultAsync(),
				User = selectedUser,
				Messages = await GetUserMessages(selectedUser.ID, 0, 1)
			};
			if (model.Messages.Count == 0)
				return NoContent();

			await SetMessageRead(read: true, fromID: selectedUser.ID, targetID: loggedUserID);

			return PartialView("_UserMessagesPartial", model);
		}

		private async Task<bool> SetMessageRead(bool read, int fromID, int targetID)
		{
			var chatRead = await _context.ChatReads
						   .Where(cr => cr.FromID == fromID && cr.TargetID == targetID)
						   .FirstOrDefaultAsync();
			bool wasRead;
			if (chatRead == null)
			{
				wasRead = read;
				await _context.ChatReads.AddAsync(new ChatRead()
				{
					FromID = fromID,
					TargetID = targetID,
					IsRead = read,
				});
			}
			else
			{
				wasRead = chatRead.IsRead;
				chatRead.IsRead = read;
				_context.Update(chatRead);
			}

			await _context.SaveChangesAsync();

			return wasRead;
		}
		[HttpGet]
		public async Task<int> GetMessageCount()
		{
			return await _context.ChatReads
					.Where(m => m.TargetID == int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value) && !m.IsRead)
					.CountAsync();
		}
	}
}

MovieApp.Web/Controllers/UserController.cs
using MemoMate.Data;
using MemoMate.Web.Models;
using MemoMate.Web.Services;
using MemoMate.Web.Models.Posts;
using MemoMate.Web.GeneralHelpers;

using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using System;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using MemoMate.Web.Models.Users;

namespace MemoMate.Web.Controllers
{
    [Authorize(Policy = "General")]
	public class UserController : Controller
	{
		private readonly MemoMateContext _context;
		private readonly PostServices _postServices;
		public UserController(MemoMateContext context, PostServices postServices)
		{
			_context = context;
			_postServices = postServices;
		}

		[HttpGet("User/Details/{username}")]
		public async Task<IActionResult> Details(string username)
		{
			if (string.IsNullOrEmpty(username))
				return RedirectToAction("Index", "Home");

			var profile = await GetProfileAsync(username);

			if (profile == null)
				return NotFound();

			return View(profile);
		}
		[HttpGet]
		public async Task<IActionResult> Likes()
		{
			var loggedUser = await _context.Users.FirstOrDefaultAsync(u => u.ID == int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value));
			var likedPosts = await _context.Likes
								   .Include(l => l.PostEntiy)
								   .Where(l => l.UserID == loggedUser.ID)
								   .OrderByDescending(l => l.ID)
								   .Select(l => new PostDetailModel
								   {
									   PostID = l.PostEntiy.ID,
									   UserID = l.PostEntiy.UserID,
									   PostDate = l.PostEntiy.Date,
									   PostRate = l.PostEntiy.RateUps * 5f / (l.PostEntiy.RateCount == 0 ? 1 : l.PostEntiy.RateCount),
									   NoteContent = l.PostEntiy.NoteEntity.Content,
									   NoteTitle = l.PostEntiy.NoteEntity.Title,
									   Username = l.PostEntiy.UserEntity.Username,
									   UserPhoto = l.PostEntiy.UserEntity.Photo,
									   ThemeName = l.PostEntiy.ThemeEntity.Name,
									   Liked = _context.Likes.Any(l => l.UserID == loggedUser.ID && l.PostID == l.PostEntiy.ID) ? "liked" : "unliked",
									   IsOwned = l.PostEntiy.UserID == loggedUser.ID,
									   CanInteract = true
								   })
								   .ToListAsync();

			if (likedPosts == null || likedPosts.Count == 0)
			{
				MessageHelpers.SetWarning("You haven't liked any posts.");
				return RedirectToAction("Index", "Posts");
			}
			foreach (var item in likedPosts)
				item.FriendStatus = await _postServices.GetFriendStatus(loggedUser.ID, item.UserID);

			UserLikesModel model = new UserLikesModel()
			{
				Posts = likedPosts,
				LoggedUserEntity = loggedUser
			};
			return View(model);
		}


		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
			HttpContext.Session.Clear();
			return RedirectToAction("Index", "Home");

		}

		private async Task<UserProfileViewModel> GetProfileAsync(string username)
		{
			var loggedUser = await _context.Users.FirstOrDefaultAsync(u => u.ID == int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value));
			var profile = await _context.Users
				.Where(u => u.Username == username)
				.Select(u => new UserProfileViewModel
				{
					LoggedUserEntity = loggedUser,
					UserID = u.ID,
					Username = u.Username,
					CreationDate = u.CreateDate,
					Mail = u.Mail,
					Photo = u.Photo,
					Posts = u.Posts.Select(p => new PostDetailModel
					{
						PostID = p.ID,
						NoteTitle = p.NoteEntity.Title,
						NoteContent = p.NoteEntity.Content,
						PostRate = p.RateUps * 5f / (p.RateCount == 0 ? 1 : p.RateCount),
						PostDate = p.Date,
						Username = u.Username,
						UserPhoto = u.Photo,

					}).ToList(),
					IsOwn = loggedUser.ID == u.ID,
				})
				.FirstOrDefaultAsync();

			profile.FriendStatus = await _postServices.GetFriendStatus(loggedUser.ID, profile.UserID);
            
			return profile;
		}

		public async Task<IActionResult> FriendRequest(string username)
		{
			if (string.IsNullOrEmpty(username) || HttpContext.Session.GetString("FollowWait") == "wait")
				return FollowError();
			HttpContext.Session.SetString("FollowWait", "wait");

			var userId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
			var targetId = await _context.Users
				   .Where(u => u.Username == username)
				   .Select(u => u.ID)
				   .FirstAsync();

			if (userId == targetId)
				return FollowError();

			var friend = await _context.Friends.Where(f => (f.UserFromID == userId && f.UserTargetID == targetId)
															|| (f.UserFromID == targetId && f.UserTargetID == userId)).FirstOrDefaultAsync();

			JsonResult result = Json(new { isSuccess = true, isAccepted = false, isWaiting = true });
			if (friend == null)
				_context.Add(new Friend { UserFromID = userId, UserTargetID = targetId, IsAccepted = false });
			else
				result = ManageFriendship(friend, userId, targetId);

			await _context.SaveChangesAsync();
			HttpContext.Session.SetString("FollowWait", "");
			return result;
		}

		private JsonResult ManageFriendship(Friend friend, int userId, int targetId)
		{
			if (friend.UserFromID == userId)
			{
				HttpContext.Session.SetString("FollowWait", "");

				_context.Remove(friend);
				return Json(new { isSuccess = true, isAccepted = false, isWaiting = false });
			}
			else if (friend.IsAccepted)
			{
				HttpContext.Session.SetString("FollowWait", "");

				_context.Remove(friend);
				return Json(new { isSuccess = true, isAccepted = false, isWaiting = false });
			}
			else
			{
				HttpContext.Session.SetString("FollowWait", "");

				friend.IsAccepted = true;
				_context.Update(friend);
				return Json(new { isSuccess = true, isAccepted = true, isWaiting = false });
			}
		}
		private JsonResult FollowError()
		{
			HttpContext.Session.SetString("FollowWait", "");
			return Json(new { isSuccess = false });
		}
		[AllowAnonymous]
		[HttpPost]
		public async Task<IActionResult> UsernameValidation(string username)
		{
			try
			{
				var isUsernameTaken = await _context.Users.AnyAsync(u => u.Username == username);
				return Json(new { isValid = !isUsernameTaken });
			}
			catch (Exception ex)
			{
				// Loglama için hata mesajı yazdırılabilir
				Console.WriteLine(ex.Message);
				return Json(new { isValid = false });
			}
		}

		[AllowAnonymous]

		[HttpPost]
		public async Task<IActionResult> UserMailValidation(string mail)
		{
			try
			{
				var isMailTaken = await _context.Users.AnyAsync(u => u.Mail == mail);
				return Json(new { isValid = !isMailTaken });
			}
			catch (Exception ex)
			{
				// Loglama için hata mesajı yazdırılabilir
				Console.WriteLine(ex.Message);
				return Json(new { isValid = false });
			}
		}

	}
}

MovieApp.Web/Views/Shared/_LoggedLayout.cshtml
@inject ISidebarService SidebarService
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memo Mate</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Oxanium:wght@200..800&display=swap" rel="stylesheet" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">

    <link href="/css/navbar.css" rel="stylesheet">
    <link href="/css/body-scrollbar.css" rel="stylesheet">
    @RenderSection("Styles", required: false)
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="main-content">
        @RenderSection("SideExtension", required: false)
        <div class="afterlayout">
            @RenderBody()
        </div>
    </div>
    @RenderSection("BottomExtension", required: false)

    <script src="https://kit.fontawesome.com/46dac6df79.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/&#64;popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous" defer></script>

    @RenderSection("Scripts", required: false)

    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.11/signalr.min.js"></script>
    <script src="/js/Message/messagehub.js"></script>
</body>
</html>

MovieApp.Web/Views/Shared/_bottombar.cshtml
@model UserEntity

<nav class="navbar fixed-bottom navbar-expand-sm navbar-dark bg-dark border-bottom-0">
	<ul class="navbar-nav mr-auto align-items-end justify-content-evenly w-100">
		<li class="nav-item">
			<a href="@Url.Action("Rates","Posts")" class="nav-link border-bottom" id="bottom-rate">
				<i class="fa-solid fa-star-half-stroke fa-xl"></i>
			</a>
		</li>
		<li class="nav-item">
			<a href="@Url.Action("Index","Posts")" class="nav-link active border-bottom" id="bottom-home">
				<i class="fa-solid fa-house fa-xl"></i>
			</a>
		</li>
		<li class="nav-item">
			<a href="@Url.Action("Create","Posts")" class="nav-link  border-bottom" id="bottom-create">
				<i class="fa-solid fa-square-plus fa-xl"></i>
			</a>
		</li>
		<li class="nav-item">
			<a href="@Url.Action("Details", "User", new { id = Model.Username })" class="nav-link border-bottom" id="dropdownUser3">
				<img src="/img/user/profile/@Model.Photo" alt="mdo" width="24" height="24" class="rounded-circle">
			</a>
		</li>
		<li class="nav-item">
			<a href="@Url.Action("Inbox", "Messages")" class="nav-link border-bottom" id="dropdownUser3">
				<i class="fa-solid fa-message fa-xl"></i>
			</a>
		</li>
	</ul>
</nav>

<script src="/js/sidebar.js"></script>

MovieApp.Web/Views/Shared/_post.cshtml
@model PostDetailModel

<div class="posts-card card text-center mb-3 h-100 shadow">
	<div class="card-header ">
		<a class="d-flex align-items-center" href="@Url.Action("Details", "User", new { id = Model.Username })">
			<div class="post-profile d-flex justify-content-center">
				<img class="h-100" src="/img/user/profile/@Model.UserPhoto" alt="Alternate Text" />
			</div>
			@Model.Username
		</a>
		@{
			if (Model.CanInteract && !Model.IsOwned)
			{
				<button class="follow-user ms-2" data-username="@Model.Username"><i class="fa-solid @Model.FriendStatus fa-lg"></i></button>
			}
		}
	</div>
	<div class="card-body">
		<div class="card-content">
			<h5 class="card-title">@Model.NoteTitle</h5>
			<p class="card-text">@Model.NoteContent</p>
		</div>
		<div class="card-theme">@Model.ThemeName</div>
	</div>
	<div class="card-footer d-flex justify-content-between text-body-secondary">
		<span class="rate text-white fw-bold">★ @Model.PostRate.ToString("0.00")</span>
		@{
			if (Model.CanInteract)
			{
				<div class="post-interactions">
					<button class="like-post" data-post-id="@Model.PostID"><i class="fa-solid fa-thumbs-up fa-xl @Model.Liked"></i></button>
					<button class="share-post"><i class="fa-solid fa-share fa-xl" style="color: #ece1ff;"></i></button>
					<button class="report-post"><i class="fa-solid fa-flag fa-xl" style="color: #FFE482;"></i></button>
				</div>

			}
		}
		<span class="date text-white fw-bold">@TimeHelpers.GetTimeAgo(Model.PostDate)</span>

	</div>
</div>

MovieApp.Web/Views/Shared/_sidebar.cshtml
@model SidebarModel

<div class="d-flex flex-column flex-shrink-0 custom-sidebar sticky-top" style="width: 4.5rem;">
	<img src="/img/logo.png" />
	<ul class="nav nav-pills nav-flush flex-column mb-auto text-center">
		<li class="nav-item">
			<a href="@Url.Action("Index","Posts")" class="nav-link active py-3 border-bottom" id="side-home">
				<i class="fa-solid fa-house fa-xl"></i>
			</a>
		</li>
		<li class="nav-item">
			<a href="@Url.Action("Rates","Posts")" class="nav-link py-3 border-bottom position-relative" id="side-rate" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Dashboard">
				<i class="fa-solid fa-star-half-stroke fa-xl"></i>
				@{
					string rateCount = GetCount(Model.NewPostCount);
					if (!string.IsNullOrEmpty(rateCount))
					{
						<span class="position-absolute badge rounded-pill bg-danger" style="top:10%; left: 65%; font-size: 0.6rem;">@rateCount</span>
					}
				}


			</a>
		</li>
		<li class="nav-item">
			<a href="@Url.Action("Create","Posts")" class="nav-link py-3 border-bottom" id="side-create" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Orders">
				<i class="fa-solid fa-square-plus fa-xl"></i>
			</a>
		</li>
		<li class="nav-item">
			<a href="@Url.Action("Likes", "User")" class="nav-link active py-3 border-bottom" id="side-likes">
				<i class="fa-solid fa-heart fa-xl"></i>
			</a>
		</li>
		<li class="nav-item">
			<a href="@Url.Action("Inbox", "Messages")" class="nav-link active py-3 border-bottom position-relative" id="side-likes">
				<i class="fa-solid fa-message fa-xl"></i>
				@{
					string messageCount = GetCount(Model.NewMessagesCount);
					<span class="position-absolute badge rounded-pill bg-danger" style="top:10%; left: 65%; font-size: 0.6rem;">@if (messageCount != null){@messageCount}</span>
				}
			</a>
		</li>
	</ul>
	<div class="dropdown border-top">
		<a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
			<img src="/img/user/profile/@Model.LoggedUserEntity.Photo" alt="mdo" width="24" height="24" class="rounded-circle">
		</a>
		<ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
			<li><a class="dropdown-item" href="@Url.Action("Settings", "User", new { id = Model.LoggedUserEntity.Username })">Settings</a></li>
			<li><a class="dropdown-item" href="@Url.Action("Details", "User", new { id = Model.LoggedUserEntity.Username })">Profile - @Model.LoggedUserEntity.Username</a></li>
			<li><hr class="dropdown-divider"></li>
			<li><a class="dropdown-item" id="signout" href="@Url.Action("Logout", "User")">Sign out</a></li>
		</ul>
	</div>
</div>

<script src="/js/sidebar.js"></script>


@{
	string GetCount(int count)
	{
		return count > 99 ? "99+" :
						count == 0 ? "" :
						count.ToString();
	}
}